### ISSUE TITLE
[M1] Intended Audience and Document Overview

### ISSUE THREAD

**Issue by RexxarAng** [ICT2201-P2-9/Music-School#13]
Describe the different types of reader that the document is intended for, such as developers, project managers, marketing staff, users, testers, and documentation writers (In your case it would probably be the “client” and the professor). Describe what the rest of this document contains and how it is organized. Suggest a sequence for reading the document, beginning with the overview sections and proceeding through the sections that are most pertinent to each reader type.

**Comment by Iphigene** [comment]
The intended audience of this document are the client and the professor. In this project, the client refers to an entity that has engaged the team to design and build a custom software according to their requirements and specifications. The professor would provide relevant and essential feedback throughout the project and documentation process for the team and ensure this document meets the stated requirements and specification. 

The team believes that section 4 would be most pertinent to the client as it encapsulates the project estimation and plan which includes the following subsections: software estimation and project management plan. These sections would give the client a rough estimation of the project cost, resources and time required before the release of the product. In general, all of the sections are pertinent to the professor for grading and reviewing the team effort and work done.

The recommended sequence for reading the document is: 1) Section 6 and 7. These sections  provide useful information regarding individual use cases descriptions and a data dictionary that consists of the different terminology used in this document to prevent any misunderstanding. 2) Section 2 illustrates the overview of the product which comprises the product overview, product functionality, assumptions and dependencies. 3) Section 3 details the requirements of the product which includes user interface requirements, functional requirements, use case model, non functional requirements, performance requirements, safety and security requirements as well as any other requirements. 4) Section 5 consists of individual team reflection regarding this project.
