### ISSUE TITLE
[M1] Assumptions and Dependencies

### ISSUE THREAD

**Issue by RexxarAng** [ICT2201-P2-9/Music-School#14]
List any assumed factors (as opposed to known facts) that could affect the requirements stated in the document. These could include third-party or commercial components that you plan to use, issues around the development or operating environment, or constraints. The project could be affected if these assumptions are incorrect, are not shared, or change. Also identify any dependencies the project has on external factors, such as software components that you intend to reuse from another project

TO DO: Provide a short list of some major assumptions that might significantly affect your design.

**Comment by genaaaaa** [comment]
The assumed factors include the following: 
A1: Management of students is not considered when designing the software.
A2: Allocation of jobs is based on the teacher's qualifications. 
A3: Allocation of workload is on a 30-minutes frame basis. 
A4: IT administrator role is purely for managing staff and manager accounts.
A5: The studio and lesson are fixed.
A6: Staff can have more than one instrument qualification. 
A7: Staff are able to indicate their availability in 30-minutes slots and range.
A8: Staff would be assigned to at least one job a month.

The team will be using Justinmind version 9.9.1 for the creation of a static web page. The web page would consist of the product prototype for the client.
