### ISSUE TITLE
[M1] Appendix A - Use Case Descriptions

### ISSUE THREAD

**Issue by RexxarAng** [ICT2201-P2-9/Music-School#16]

**Comment by genaaaaa** [comment]
1. View Staff Workload
2. Allocate Job
3. Reallocate Job
4. View Staff Availability
5. View Assigned Jobs
6. View Overall Workload
7. Reject Job Assigned
8. Add Availability
9. Indicate Job Preference
10. Edit Availability
11. View Availability
12. View Accounts
13. Edit Accounts
14. Delete Accounts
15. Create Accounts
