### ISSUE TITLE
[M1] Project Estimation and Plan

### ISSUE THREAD

**Issue by RexxarAng** [ICT2201-P2-9/Music-School#18]
Describe the resources required and overall time required for the project.

**Comment by genaaaaa** [comment]
The software estimation comprises the estimation of size and estimation of effort. The process of size estimation is shown in the following steps 1-4. 
Therefore, the calculation of Use Case Points (UCP) = UUCW *  TCF * EF
							         = 101 * 1.0 * 0.77 = 77.77 = 78 (nearest whole number)
The effort was estimated using UCP where an estimation of 20 hours was given to each UCP. The estimated effort in developer-hours of a project of size 78 UCP = 20 * 78 = 1560 hours
