### ISSUE TITLE
Client Meeting

### ISSUE THREAD

**Issue by RexxarAng** [ICT2201-P2-9/Music-School#2]
Q: [What is the current process of performing work allocation in the music school? Are there any pre-existing systems that you are using?]
A: On paper to track work allocation. No pre-existing systems.

The manager should be able to visualise the staff workload immediately on the landing page
Q: [Prototype: All staff workload or based on a search feature for a particular staff?]
A: To highlight demand by showing workload hours for the different types of instruments. Top 3 staff with highest workload shown.

The manager should be able to view up to three staff availability and any relevant information (apart from job preference) to make the job assignment easier on the job allocation page.
Q: [Staff availability of 1 week, 2 week ?]
A: Should be able to view staff’s availability for the particular week, can click to view more staff’s availability

Q: [What is any relevant information?]
A: Studio Rooms available (Only 1 room can conduct drum lessons), workload allocated to the staff, staff’s qualifications (if they can teach more than one instrument), other jobs already allocated to the staff to ensure they don’t exceed four hours of work without 1 hour of rest, the current allocated workload for the week.

Staff can indicate their job preference for the week
Q: [As in the number of working hours or the sessions that they want? Or what type of job/tasks they want to do? Or both ?]
A: They can indicate how many working hours they want, manager can only underload them and not overload them

Q: [Follow up with the previous Q, if it is the type of job/tasks they want to do, do we have to indicate a list of available jobs or the staff would specify?]
A: Based on their qualification

Q: [How does the teachers indicate their availability? Morning/Afternoon shift or hourly availability?]
A: By 30 minute slots, perhaps a range can be chosen

Staff can reject jobs assigned to them, but will be warned to discuss the jobs with their manager before proceeding with the rejection 
Q: [Is this warning or just a prompt to the staff]
A: A prompt will be sent to the manager so that they will be notified

Q: [Does the manager have to accept the staff's rejection before the staff can drop the job on the system?]
A: The manager can choose to reallocate the job that the staff reject every Thursday morning by the end of friday, the staff have to reject the job assigned to be considered by the manager. If no other teacher can be assigned, then they will still be allocated the job.

The company's IT administrator will oversee adding new staff and managers to the system 
Q: [Is this manual, adding into the database? or is it an additional role where an administrator has their own login, and have respective functionalities to add through the website?]
A: New admin portal

Q: [If the administrator has their own login, is it purely just for adding new staff and managers or is there any other functionalities?]
A: Purely adding new staff and manager. Only necessary details for staff and manager.

Q: [Does this system also need to support manager managing students joining classes? Is there a standard class time for the different types of lessons?]
A: No, the managers will manually manage the students.

Q: [What does the new unassigned students mean under each instrument? {actually not sure if this matters in any way)]
A: It is important information for the managers to take note to assign students (contradictory to q8, the client might actually need to manage students in the system

Q: [For job allocation, is the studio and lesson fixed and the only change is the teachers ?]
A: Fixed classes

Non-functional Requirement

- Multi language support not needed
- 2FA
- Enforce strong password policy:
At least 1 special character/symbol 
At least 8 characters 
At least 1numbers 
Need to include uppercase and lowercase letters 
Change password after 90 days
- Maintenance timing should not happen during opening hours and 1 hour before/after the opening hours
- Application should be mobile-friendly
- Application should be reasonably easy to use, as staffs comes and goes, manual to operate the system
- Backup data is important
- Server downtime during crash is not important, within a day to recover
- Security > performance, encryption for personal data for staff/manager

**Comment by Iphigene** [comment]
Finalize and update client meeting questions from team's google docs [Planning]
https://docs.google.com/document/d/1DKtHJk5i8iBWu9NyFY5gozaTUT3kIPiXOjSThMN8kTg/edit

**Comment by RexxarAng** [comment]
**Client Meeting Minutes**
Date: 13/09/22
Time: 17:00
Present: Alex, Iphigena, Iphigene
Absent: Nil
Purpose: Clarify user requirements

Functional Requirements
1. Client is currently using paper to do work allocation management, and not using any pre-existing systems for work allocation management
2. Manager needs to be able to see the top three staff with highest workload and see the workload hours allocated to the different types of instruments
3. Manager should be able to view the staff's availability for the week that they are trying to assign to the staff, and they can view more than 3 staff's availability during the job allocation. (initially show 3, click "more" to show more staff's availability)
4. Relevant information for making job assignment easier on the job allocation page includes the studios' availability, total workload hours allocated to the staff, staff's qualification, other jobs allocated to the staff (ensure that they don't work consecutively for more than 4 hours without rest)
5. Staff indicating their job preference by indicating their availability in 30 minute slots.
6. When the staff reject the job, a prompt will be sent to the manager and the manager will have to manually reallocate the job task before the job is  unassigned to the staff.
7. Job allocation is done every Thursday morning, and the staff can only reject from Thursday morning till Friday evening.
8. IT administrator is required to have a portal to add and remove managers/staffs (contain more information than what is shown to the manager such as bank details, nric, etc). Oversight of the whole system.
9. Manager need to manage students to assign student to classes and as well as removing them from classes
10. Lessons are fixed every week, the change is only the staff.

Non Functional requirements
1. Multi language support not needed
2. 2 FA
3. Enforce strong password policy:
At least 1 special character/symbol 
At least 8 characters 
At least 1numbers 
Need to include uppercase and lowercase letters 
Change password after 90 days
4. Maintenance timing should not happen during opening hours and 1 hour before/after the opening hours
5. Application should be mobile-friendly
6. Application should be reasonably easy to use, as staffs comes and goes, manual to operate the system
7. Backup data is important
8. Server downtime during crash is not important, within a day to recover
9. Security > performance, encryption for personal data for staff/manager
