### ISSUE TITLE
[M2] Improve the product scope  (M1 Update)

### ISSUE THREAD

**Issue by RexxarAng** [ICT2201-P2-9/Music-School#26]
improve product scope by redefining it to be specifically on the problem domain (Music School) in the M1 report

**Comment by genaaaaa** [comment]
The scope of the product is to create a web-based application that will be utilised by
managers, staff and IT administrators for workload allocation in the Music School. 

The employees of Music School should be able to see their job assignments and working hours engaged/assigned. They will also be able to indicate their availability up to one month earlier and indicate if they cannot fulfil any assigned jobs. This product would greatly benefit the employees as they will now have a clear overview of their work schedules, allowing them to plan both days off and working days conveniently.  

In addition, the managers should be able to visualise the manpower availability up to one month earlier, as well as job assignments and allocate jobs. This product would benefit managers as they are able to view regular updates on staff availability and engagement more effectively, allowing them to follow up and plan an optimised workload schedule.

Furthermore, the IT administrators will oversee staff and managers accounts by creating, editing or removing them. This product would be useful for the IT administrators as they could manage accounts more efficiently as all accounts are in a centralised system.
