### ISSUE TITLE
[M2] Include Requirement Elicitation Methods (M1 Update)

### ISSUE THREAD

**Issue by RexxarAng** [ICT2201-P2-9/Music-School#27]
Include requirement elicitation methods that were used during the client meeting

**Comment by Iphigene** [comment]
<M1 update for requirements elicitation method>
The process of requirement discovery is crucial to focus on and understand what the client needs for the product. Hence, the team has utilized several requirements elicitation methods to derive the required requirements. 

The first requirement elicitation method utilized was via Documents. The team was given a document with an overview of the project descriptions which includes most of the functional system requirements and user requirements. The document provides the team with an understanding of the problem domain and business functionality which aids in the initial process of requirement discovery and provides the essential materials for the second requirement elicitation method. 

The second requirement elicitation method utilized was conducting interviews. A client meeting was set during the second week of the assignment to gather user interface requirements, functional and nonfunctional requirements, performance requirements, and safety and security requirements. This elicitation method is beneficial for the team as it provides the team with the opportunity to clarify requirements and doubts on the documentation provided by the client through face-to-face interaction.

The third requirement elicitation method utilized was prototyping. This elicitation method allows the team to first create a prototype based on the known requirements and specification for the client. The prototype is built quickly and showcased to the client during the client meeting to gather feedback and opinions regarding the mock up product. The prototype gives a clearer picture of what the client needs, and at the same time, provides assurance to the client as well as the team on the direction of the project.
