### ISSUE TITLE
[M2] Improvement of use case descriptions (M1 Update)

### ISSUE THREAD

**Issue by RexxarAng** [ICT2201-P2-9/Music-School#28]
Improve clarity of use case descriptions, remove steps that should have occurred before the use case

**Comment by genaaaaa** [comment]
**1. View Staff Workload**
**2. Allocate Job** (removed include relationship with UC4 and steps that should have occurred before the use case, added extension point for UC3)
**3. Reallocate Job**
**4. View Staff Availability** (removed steps that should have occurred before the use case)
**5. View Assigned Jobs** (removed steps that should have occurred before the use case)
**6. View Overall Workload** (removed steps that should have occurred before the use case)
**7. Reject Job Assigned** (removed steps that should have occurred before the use case)
**8. Add Availability** (added extension point for UC9, removed steps that should have occurred before the use case)
**9. Indicate Job Preference** (removed steps that should have occurred before the use case)
**10. Edit Availability**
**11. View Availability** (removed steps that should have occurred before the use case)
**12. View Accounts** (removed steps that should have occurred before the use case)
**13. Edit Accounts** (removed steps that should have occurred before the use case)
**14. Delete Accounts** (removed steps that should have occurred before the use case)
**15. Create Accounts** (removed steps that should have occurred before the use case)
