### ISSUE TITLE
[M2] Improvement user interface requirements (M1 Update)

### ISSUE THREAD

**Issue by RexxarAng** [ICT2201-P2-9/Music-School#30]
Specifically more details on the user interface, that will impact the design of the webpage. Includes descriptions of how the prototype achieves those requirements

**Comment by Iphigene** [comment]
The user interface requirements (UR) includes the following:

UR1: The system shall use a colour theme of red, blue, orange, green, purple, grey, black and white.  
UR2: The system shall use a background page that shows different types of instruments.
UR3: The system shall support mobile applications and web browsers.
UR4: The system shall use black fonts for wordings and title.
UR5: The system shall include drop-down menus and buttons to assist the selection of options.
