### ISSUE TITLE
[M2] Update gantt chart for project schedule (M1 Update)

### ISSUE THREAD

**Issue by RexxarAng** [ICT2201-P2-9/Music-School#39]
Include estimated timeline for M2 and M3 in gantt chart

**Comment by Iphigene** [comment]
![Image](https://user-images.githubusercontent.com/90232371/196597678-047332f1-27a5-453f-ad41-04bc70cd45e8.jpg)

**Comment by RexxarAng** [comment]
https://docs.google.com/spreadsheets/d/15xkLJZG4X5CLQtZBZ6TNBd1K7kNLxlnH6iUAtg21R34/edit?usp=sharing
