### ISSUE TITLE
[M2] Staff's Sequence Diagram

### ISSUE THREAD

**Issue by RexxarAng** [ICT2201-P2-9/Music-School#42]
To use sequence diagram to explain design flow between staff and other objects as well as writing to explain the sequence diagram

**Comment by genaaaaa** [comment]
![Image](https://user-images.githubusercontent.com/91716039/198681872-07727592-ee8c-4e05-b799-ed307d2b479e.png)



![Image](https://user-images.githubusercontent.com/91716039/198681960-5d8d69d3-56d6-40e6-b23b-289bea434fa8.png)



![Image](https://user-images.githubusercontent.com/91716039/198682000-8046daf5-909c-486b-a405-e725c2e6d13d.png)
