### ISSUE TITLE
[M2] Iphigene's Task Reflections

### ISSUE THREAD

**Issue by RexxarAng** [ICT2201-P2-9/Music-School#47]
Each member is required to write no more than 2 paragraphs of what they have done for milestone one, what they have learned, how they were to do it differently if they are given another chance to do it again, and as a team what can be done better.

**Comment by Iphigene** [comment]
For milestone two, I was in charge of setting at least a day every week to have a meeting either online via discord or physically for a progress update on the tasks. In addition, I completed the updates from the milestone one report and project plan section, as well as various diagrams, such as the component and sequence diagrams. I learned the difference between each diagram presented in the report and how to use the mentioned diagrams to illustrate the sequence and flow of the use case descriptions. I learned the importance of drawing these diagrams as they are essential in depicting and giving a better overview of the software design. 

I believe we can complete the diagrams earlier and more accurately at the beginning of the assignment, given a better understanding of the different diagrams and when to utilise the mentioned diagrams. As a team, we made significant improvements from milestone one and managed to clarify any questions we had when in doubt. For milestone three, I believe the team can further improve by arranging consultation sessions and planning buffer time for any overruns.
