### ISSUE TITLE
[M2] Project Plan

### ISSUE THREAD

**Issue by RexxarAng** [ICT2201-P2-9/Music-School#48]
Describe the resources required and overall time required for the project. Include the current status of the project and work allocations. Highlight any overruns and explain the reasons

**Comment by Iphigene** [comment]
The project plan section would describe the Software Development Life Cycle (SDLC), resources required and overall time required for the project via effort estimation and estimated time duration. The section would also include the current status of the project with a gantt chart as well as the work allocation for this project via the work breakdown structure (WBS) diagram. In addition, explanation of any overruns of the project will also be included.

4.1	SDLC
The software development life cycle chosen for this project is Rational Unified Process (RUP) model with the focus on delivering high quality software through object-oriented models with its design and documentation expressed using Unified Modelling Language (UML). This allows the business process to be tied to the development process and delivery value early to the client while focusing on the quality of design which is suitable in this project. In addition, it does not require close collaboration with the client which the client prefers for this project and our team has experience in object-oriented programming which is beneficial for this SDLC model. In conclusion, with the strict timeline and budget that this project has, this model is the most suitable as this project has three specific milestones that can be achieved using this model with the required specifications composing of many UML diagrams.

Estimation of Task Duration
Based on the three point estimation model, the team has decided:
1. The Optimistic duration (OD) is 20 days.
2. The Pessimistic duration (PD) is 30 days.
3. The expected duration (ED) is 22 days.

Hence the weighted average of the most likely duration (D) as follows:
𝐷 = (1 × 𝑶𝑫) + (4 × 𝑬𝑫) + (1 × 𝑷𝑫) /6
𝐷 = (12 + (4 * 15) + 27) / 6
𝐷 = 23 days
https://www.projectengineer.net/estimating-task-durations/


Project Overruns
The duration for the creation of individual diagrams such as architectural design, component diagram, sequence diagrams and detailed design had overran as new changes were made throughout the assignment period, specific requirements changes would also be reflected and directly affect the changes in the mentioned diagrams.
