### ISSUE TITLE
[M2] Specific Requirements

### ISSUE THREAD

**Issue by RexxarAng** [ICT2201-P2-9/Music-School#49]
Only include the new requirements and changes to requirements from M1 (including requirements you have removed). If the requirements affect your use case diagram, include your updated use case diagram in this section and your updated use case descriptions in the appendix. 

Please describe all changes and new additions

**Comment by genaaaaa** [comment]
This section details the new and changed requirements of the product which includes user interface requirements, functional requirements, updated use case model, non functional requirements, performance requirements, and safety and security requirements.

**Requirements Elicitation Method**
The process of requirement discovery is crucial to focus on and understand what the client needs for the product. Hence, the team has utilized several requirements elicitation methods to derive the specific requirements. 

The first requirement elicitation method utilized was via Documents. The team was given a document with an overview of the project descriptions which includes most of the functional system requirements and user requirements. The document provides the team with an understanding of the problem domain and business functionality which aids in the initial process of requirement discovery and provides the essential materials for the second requirement elicitation method. 

The second requirement elicitation method utilized was conducting interviews. A client meeting was set during the second week of the assignment to gather user interface requirements, functional and nonfunctional requirements, performance requirements, and safety and security requirements. This elicitation method is beneficial for the team as it provides the team with the opportunity to clarify requirements and doubts on the documentation provided by the client through face-to-face interaction.

The third requirement elicitation method utilized was prototyping. This elicitation method allows the team to first create a prototype based on the known requirements and specification for the client. The prototype is built quickly and showcased to the client during the client meeting to gather feedback and opinions regarding the mock up product. The prototype gives a clearer picture of what the client needs, and at the same time, provides assurance to the client as well as the team on the direction of the project. 

**Product Overview**
The product is a web-based application replacing paper records and manual processes. The web-based application will be built with ExpressJS which is a minimal and flexible Node. js web application framework that provides a robust set of features for web and mobile applications. The web server will be hosted in Application instances run within Docker containers on Compute Engine virtual machines (VM).

Figure 1: System Architecture Diagram

Figure 1 presents an overall view of the system architecture. The web-based workload management system provides functionalities that are stated in Section 2.2 Product Functionality. It has interfaces to the external system, such as the Cloud Database System. The web-based workload management system stores all its data in the Cloud Database System and is therefore essential to maintain connection to it. The team would be using Google Cloud as its cloud database as it provides AES256 encryption for data stored in the database. This would ensure that the stored data is more secure and safe for the company.

**User Interface Requirements**
The user interface requirements (UR) includes the following:

UR1: The system shall use a colour theme of red, blue, orange, green, purple, grey, black and white.  
UR2: The system shall use a background page that shows different types of instruments.
UR3: The system shall support mobile applications and web browsers.
UR4: The system shall use black fonts for wordings and title.
UR5: The system shall include drop-down menus and buttons to assist the selection of options.
 
**Functional Requirements**
This section consists of all the functional requirements (FR) that capture the intended behaviour of the system.

FR1: The system shall display job assignments in a weekly schedule in the landing page to the staff.
FR2: The system shall display overall workload in the landing page to the staff
FR3: The system shall allow staff to submit their available dates with the respective time slots up to 5 weeks in advance.
FR4: The system shall allow staff to reject jobs allocated to them from Thursday to Friday each week to send a prompt to notify the manager.
FR5: The system shall allow staff who are qualified to teach more than one instrument to indicate their preference on which lesson they prefer to teach.
FR6: The system shall display information about the overall workload allocated for different instruments in the landing page to the manager.
FR7: The system shall highlight the top three staff with highest workload in the landing page to the manager
FR8: The system shall allow managers to allocate jobs to staff in 30 minute sessions while checking if the staff exceeded four consecutive hours of work without rest and an available studio is allocated to the job.
FR9: The system shall allow managers to view staff’s workload such as jobs assigned, workload allocated in hours and availability.
FR10: The system shall allow IT administrators to manage the user accounts.

**Updated Use Case Model**
The use case model diagram in Figure 2 is an updated version of the model from milestone one. The changes include the addition of extension points in the diagram.

Figure 2:  Use Case Model

**Non-functional Requirements**
The non-functional requirements (NFR) include the following:
NFR1: The system shall present content in English.
NFR2: The system shall be designed with responsive design and mobile-friendly for all types of mobile devices such as mobile phones and tablets.
NFR3: The users shall be able to use all the system functions after one hour of training. After this training, the average number of errors made by experienced users shall not exceed two per hour.

**Performance Requirements**
The performance requirements include the following:
NFR4: The server will recover after experiencing a crash or denial of service within 24 hours

**Safety and Security Requirements**
The safety and security requirements include the following:
NFR5: Confidential data stored in the database shall be encrypted with AES-256.
NFR6: All approving roles must use a different factor of authentication from the user authentications (on top of 2FA) for approval processes.
NFR7: The system shall have multi-factor authentication (MFA).
NFR8: The system shall enforce strong password policy where passwords have to contain:
At least 1 special character/ symbol
At least 8 characters (Mixture of uppercase and lowercase)
At least 1 number
Change password every 90 days
NFR9: The data stored in the database shall be backed up to prevent data loss.
NFR9: The website shall have a Secure Sockets Layer (SSL) certificate to secure communications between the web server and client.
