### ISSUE TITLE
[M3] Black Box Testing

### ISSUE THREAD

**Issue by RexxarAng** [ICT2201-P2-9/Music-School#53]
This section should include a carefully constructed system state diagram which is clearly informed by your use cases.  The state diagram should inform the test cases that have been chosen which will allow for comprehensive black box testing, with each and every test case clearly define following guidelines covered during the class sessions

**Comment by RexxarAng** [comment]
System State Diagram


![Image](https://user-images.githubusercontent.com/24503925/204020070-fa1ceb51-cd51-48f0-8ba7-b3012eb6527c.png)

**Comment by RexxarAng** [comment]
Blackbox Testing can be found here

https://docs.google.com/spreadsheets/d/1Zceb3GKUQwWTJHC8dCKDoqS9djfsKy7mEwZOLCYeV-k/edit?usp=sharing

**Comment by Iphigene** [comment]
![Image](https://user-images.githubusercontent.com/90232371/204087023-f2ae912e-f1de-453e-b60a-ffcfccc9f135.png)

**Comment by Iphigene** [comment]
![Image](https://user-images.githubusercontent.com/90232371/204087041-41b169ff-2cb2-40d7-8947-08242712b246.png)

**Comment by Iphigene** [comment]
![Image](https://user-images.githubusercontent.com/90232371/204087074-17c204d3-167a-4558-8e76-aae322cf1d03.png)

**Comment by Iphigene** [comment]
![Image](https://user-images.githubusercontent.com/90232371/204087088-6845e4c1-99e0-4972-b72f-1c985a6e42f4.png)

**Comment by Iphigene** [comment]
![Image](https://user-images.githubusercontent.com/90232371/204087130-a807a258-f9de-4916-9c32-0cc56f50dd20.png)

**Comment by Iphigene** [comment]
![Image](https://user-images.githubusercontent.com/90232371/204087140-dd3d8a48-90de-49a4-80a2-090dc6855ea4.png)
