### ISSUE TITLE
[M3] Prototype (Staff)

### ISSUE THREAD

**Issue by RexxarAng** [ICT2201-P2-9/Music-School#56]
Staff prototype includes the staff's dashboard, staff's job availability and preference pages

Dashboard Page

- Staff to view their weekly job assignments and overall workload for the month on the landing page

Availability and Preference Page

- Allow Staff to add and edit their availabilities up to 5 weeks ahead of time, as well as indicating their job preference for the week.

**Comment by genaaaaa** [comment]
Staff
The following wireframes will demonstrate the use cases UC5-10: View Overall Workload, Reject Job Assigned, Add Availability, Indicate Job Preference, Edit Availability and View Availability.

Dashboard Page

The Staff Dashboard Page, as shown in Figure 9, is displayed after the staff has logged in. The staff will be able to view their weekly job assignments and overall workload for the month. The staff can reject jobs assigned to them, but they will be warned to discuss the jobs with their
manager before proceeding with the rejection, as shown in Figure 10. In the dashboard, the staff is able to view overall workload, reject job assigned and view availability,


Figure 9: Staff Dashboard Page


Figure 10: Staff Dashboard Page Warning Message






Add Availability Page

The Staff Add Availability Page, as shown in Figure 11, is displayed after the staff chooses to add their availability. The staff will be able to select the date and time slots in 30 mins intervals up to 5 weeks ahead of time. After submitting their availability, a green confirmation message “Availability Added Successfully” will be displayed when the system added their availability into the database. In this page, the staff is able to add availability into the system.


Figure 11: Staff Add Availability Page

Indicate Job Preference Page

The Staff Indicate Job Preference Page as shown in Figure 12, is displayed after the staff chooses to indicate preference. The staff will be able to view the qualifications that they have, indicated as green boxes. Thereafter, they can select one or more instruments that they are qualified for as their job preference for the week. After submitting their job preference, a green confirmation message “Preference Indicated Successfully” will be displayed after the system added their preferences into the database. 


Figure 12: Staff Indicate Job Preference Page

View and Edit Availability Page

The Staff View and Edit Availability Page as shown in Figure 13, is displayed after the staff chooses to view availability. The staff is able to view and edit availability up to 5 weeks ahead of time that were previously submitted by them. After viewing their availability, the staff can choose to edit them by selecting the modify option next to the specific date. Thereafter, time slots will be available for the staff to reselect their timings. After submitting their new availability, a green confirmation message “Edit Availability Successfully” will be displayed after the system modified the availability of the staff in the database. 


Figure 13: Staff View and Edit Availability Page
