### ISSUE TITLE
[M3] Prototype (IT Admin)

### ISSUE THREAD

**Issue by RexxarAng** [ICT2201-P2-9/Music-School#57]
IT Admin Prototype includes page to create, read, update and delete employees

**Comment by genaaaaa** [comment]
IT Administrator
The following wireframes will demonstrate the use cases UC11-15: View Accounts, Add Accounts, Edit Accounts and Delete Accounts.

Dashboard Page

The IT Administrator Dashboard Page, as shown in Figure 14, is displayed after the staff has logged in. The IT Administrator will oversee adding new staff and managers to the system as well as managing accounts. 


Figure 14: IT Admin Dashboard Page

Create Account Page
The IT Administrator Create Account Page as shown in Figure 15, is displayed after the IT administrator chooses to create an account. For the input fields, the IT administrator can select either “Manager” or “Staff” for the Staff role, the staff/manager ID for the Staff ID, the qualification for the Staff qualification if creating a staff account, the staff/manager name for the Staff name, the staff/manager email for the Staff email, the staff/manager contact information for the Staff contact, and lastly the password for the Staff password. 

After submitting the new account information, a green confirmation message “Account Created Successfully” will be displayed after the system adds the account into the database. Thereafter, the system will send an email to the account’s email with the login details of the account. 









Figure 15: IT Admin Create Account Page

Manage Account Page

The IT Administrator Manage Account Page as shown in Figure 16, is displayed after the IT administrator chooses to manage an account by viewing, editing or deleting accounts. 


Figure 16: IT Admin Manage Staff Account Page


Figure 17: IT Admin Manage Manager Account Page
