### ISSUE TITLE
[M3] Iphigena's Task Reflections

### ISSUE THREAD

**Issue by RexxarAng** [ICT2201-P2-9/Music-School#59]
Each member is required to write no more than 2 paragraphs of what they have done for milestone one, what they have learned, how they were to do it differently if they are given another chance to do it again, and as a team what can be done better.

**Comment by genaaaaa** [comment]
For milestone 3, I was in charge of all the users’ prototypes which included Manager, Staff and IT Administrator, and recording and editing of the 3-min prototype video. I also made changes to the system state diagram and report. Throughout this milestone, I understood how tedious and extensive it is to ensure that the prototype is following all the mentioned use cases and requirements. This helped me to understand how a real web application could be like in real life as creating a prototype greatly simulated the process. 

If given a chance to do it again, I would double check the requirements from the very start so as to avoid rechecking the prototype multiple times at the end . As a team of only 3 team members, the workload was quite intensive for the team as everyone had to work on multiple tasks at one go.
