### ISSUE TITLE
[M3] Prototype (Common)

### ISSUE THREAD

**Issue by RexxarAng** [ICT2201-P2-9/Music-School#61]
The common prototype consists of the login page

Login Page

- Allow Manager, Staff and IT Admin to login to access the system

**Comment by genaaaaa** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-35c847d4-7fff-dd12-ec37-c4ecfe944771"><h2 dir="ltr" style="line-height:1.2;text-indent: -28.8pt;margin-top:14pt;margin-bottom:14pt;padding:0pt 0pt 0pt 28.8pt;"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Main</span></h2><p dir="ltr" style="line-height:1.2;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Login Page</span></p><br /><p dir="ltr" style="line-height:1.2;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Upon visiting the Music School website, the users (Manager, Staff and IT Admin will see a login page, as shown in Figure 4. The different users will see different features and functionality of the website according to their role in the company.&nbsp; For this prototype, we will be able to access the respective user accounts, shown in the Table below, based on the input we entered in the Email field and the tabs that the user has selected.&nbsp;</span></p><br /><div dir="ltr" style="margin-left:0pt;" align="left">

Email | Account
-- | --
manager@musicschool.com | Manager
staff@musicschool.com | Staff
admin@musicschool.com | IT Administrator

</div><p dir="ltr" style="line-height:1.2;text-align: center;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Table 25: Email and Account</span></p><br /><p dir="ltr" style="line-height:1.2;text-align: center;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:1pt solid #000000;display:inline-block;overflow:hidden;width:643px;height:341px;"><img src="https://lh6.googleusercontent.com/xdx9VRmwMbpgD6Yb3vJ5uH_HARhGfCmE7rZbu1N-cKoTG8rlJCVGxpWASokgoY15zU37dR-0ESDdnUsnZFtcjcnH2uxlrSdEpFrhprGAaJFUBJBb4pGzCqBJSZI6uHyh8SLRPvbReeoVOkKw4gznySTWVzpHBWLufArgzupepCXLTUnlwm1S9YmaJyHYOqq3" width="643" height="341" style="margin-left:0px;margin-top:0px;" /></span></span></p><p dir="ltr" style="line-height:1.2;text-align: center;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Figure 4: Login Page</span></p><br /><p dir="ltr" style="line-height:1.2;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Forget Password Page</span></p><br /><p dir="ltr" style="line-height:1.2;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The Forget Password Page, as shown in Figure 5, is displayed if the user clicked on the &ldquo;Forget Password?&rdquo; button shown in the above figure. The users will be prompted to enter their email and mobile phone number to recover their password. Following which, they will be redirected back to the Login Page once they are clicked on the &ldquo;Done&rdquo; button.</span></p><br /><p dir="ltr" style="line-height:1.2;text-align: center;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:1pt solid #000000;display:inline-block;overflow:hidden;width:643px;height:263px;"><img src="https://lh5.googleusercontent.com/9EIJaUqP49nm_UN4Gc42-gqae9mz-uplJdWxYy3X3GSrT-xSTPafDOSgbDfnoDTkIP6zzWeq5_tn1z2yvPfsYF_n2-9SyzX2Nch5tOFy-0UiFtuabkvafdPBOvL-v51R9FOCCFL-uFIFnywg-6d3dDZtQGVjjeKjlurYO1kDEzzV45T2jK1AEr997Ud32THf" width="643" height="263" style="margin-left:0px;margin-top:0px;" /></span></span></p><p dir="ltr" style="line-height:1.2;text-align: center;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Figure 5: Forget Password Page</span></p></b><br class="Apple-interchange-newline">
</body>
</html>
