### ISSUE TITLE
[M1] Product Overview

### ISSUE THREAD

**Issue by RexxarAng** [ICT2201-P2-9/Music-School#7]
Describe the context and origin of the product being specified in this document. For example, state whether this product is a follow-on member of a product family, a replacement for certain existing systems, or a new, self-contained product. If the document defines a component of a larger system, relate the requirements of the larger system to the functionality of this software and identify interfaces between the two. In this part, make sure to include a simple diagram that shows the major components of the overall system, subsystem interconnections, and external interface. In this section it is crucial that you will be creative and provide as much information as possible

TO DO: Provide at least one paragraph describing product perspective. Provide your **System’s Architecture diagram** to illustrate how your product interacts with the environment and in what context it is being used.  This is not a formal diagram, but rather something that is used to illustrate the product at a high level.

**Comment by genaaaaa** [comment]
The product is a web-based application replacing paper records and manual processes. The web-based application will be built with ExpressJS which is a minimal and flexible Node. js web application framework that provides a robust set of features for web and mobile applications.

Figure 1 presents an overall view of the system architecture. The web-based workload management system provides functionalities that are stated in Section 2.2 Product Functionality. It has interfaces to the external system, such as the Cloud Database System. The web-based workload management system stores all its data in the Cloud Database System and is therefore essential to maintain connection to it. The team would be using Google Cloud as its cloud database as it provides AES256 encryption for data stored in the database. This would ensure that the stored data is more secure and safe for the company.
